# Generated by Django 5.1.6 on 2026-02-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='fire_token',
        ),
        migrations.CreateModel(
            name='SiteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=80, unique=True)),
                ('type', models.CharField(choices=[('public', 'Public Portal'), ('staff', 'Staff Management'), ('keypad', 'Staff Keypad Sign-In'), ('fire', 'Fire Roll Call')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.site')),
            ],
            options={
                'unique_together': {('site', 'type')},
            },
        ),
    ]
