# Generated by Django 5.1.6 on 2026-02-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_site_fire_token_sitetoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteQR',
        ),
    ]
