# Generated by Django 5.1.6 on 2026-02-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_siteqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='confidentiality_terms',
            field=models.TextField(blank=True, default='', help_text='Custom confidentiality terms for this site. Shown on sign-in forms.'),
        ),
        migrations.AddField(
            model_name='site',
            name='health_safety_procedures',
            field=models.TextField(blank=True, default='', help_text='Health and safety procedures for this site. Shown on sign-in forms.'),
        ),
    ]
