# Generated by Django 6.0.2 on 2026-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_site_confidentiality_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemanager',
            name='pin',
            field=models.CharField(blank=True, help_text='Optional PIN for site manager actions', max_length=12, null=True),
        ),
    ]
