# Generated by Django 6.0.2 on 2026-02-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitemanager_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='fire_rollcall_cutoff_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutes after sign-out to include someone in the fire roll call list'),
        ),
    ]
