# Generated by Django 5.1.6 on 2026-02-09 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.site'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.site'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='access.staffmember'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['site', 'name'], name='access_staf_site_id_ea85a4_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['site', 'pin_value'], name='access_staf_site_id_e725e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffmember',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='uniq_staff_name_per_site'),
        ),
        migrations.AddConstraint(
            model_name='staffmember',
            constraint=models.UniqueConstraint(fields=('site', 'pin_value'), name='uniq_pin_per_site'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['site', '-occurred_at'], name='access_acce_site_id_19d1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['staff', '-occurred_at'], name='access_acce_staff_i_cb5548_idx'),
        ),
    ]
