# Generated by Django 5.1.6 on 2026-02-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_clockout_field'),
        ('access', '0002_initial'),
    ]

    operations = [
    ]
