# Generated by Django 5.1.6 on 2026-02-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_merge_0002_auto_clockout_field_0002_initial'),
        ('core', '0004_delete_siteqr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('company', models.CharField(blank=True, default='', max_length=160)),
                ('work_description', models.CharField(blank=True, default='', max_length=255)),
                ('confidentiality_signed', models.BooleanField(default=False)),
                ('signed_in_at', models.DateTimeField(blank=True, null=True)),
                ('signed_out_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('company', models.CharField(blank=True, default='', max_length=160)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('confidentiality_signed', models.BooleanField(default=False)),
                ('signed_in_at', models.DateTimeField(blank=True, null=True)),
                ('signed_out_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='core.site')),
            ],
        ),
    ]
