# Generated by Django 5.1.6 on 2026-02-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_contractor_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='checkout_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
