# Generated by Django 6.0.2 on 2026-02-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_contractor_checkout_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='is_associated',
            field=models.BooleanField(default=False, help_text='Flag for associated staff (no PIN required)'),
        ),
    ]
