# Generated by Django 6.0.2 on 2026-02-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_staffmember_is_associated'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='association_type',
            field=models.CharField(blank=True, choices=[('locum', 'Locum'), ('trainee', 'Trainee'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
