# Generated by Django 6.0.2 on 2026-02-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_staffmember_association_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='checkout_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
