# Generated by Django 6.0.2 on 2026-02-11 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_staffmember_checkout_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessevent',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='access.staffmember'),
        ),
    ]
