# Generated by Django 6.0.2 on 2026-02-11 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_alter_accessevent_staff'),
        ('core', '0006_sitemanager_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('company', models.CharField(blank=True, default='', max_length=160)),
                ('work_description', models.CharField(blank=True, default='', max_length=255)),
                ('confidentiality_signed', models.BooleanField(default=False)),
                ('signed_in_at', models.DateTimeField(blank=True, null=True)),
                ('signed_out_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('checkout_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_staff', to='core.site')),
            ],
        ),
    ]
