# Generated by Django 6.0.2 on 2026-02-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0011_associatedstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associatedstaff',
            name='company',
        ),
        migrations.AddField(
            model_name='associatedstaff',
            name='association_type',
            field=models.CharField(blank=True, choices=[('locum', 'Locum'), ('trainee', 'Trainee'), ('pcn', 'PCN')], default='pcn', max_length=32),
        ),
    ]
